updating DApp capitalization to standard use
Chia-Network/chia-docs pull request #237
Opened 2023-01-20 20:49 UTC by roybotbot

DApp -> dApp

2023-01-20 21:00 UTC, hoffmang9 requested changes
Good after the 404'd images issue is managed

2023-01-20 21:00 UTC, hoffmang9 commented on docs/guides/walletconnect/walletconnect-user-guide.mdx
> +  info  - Loaded env from C:\Users\User\Documents\GitHub\chia\chia-wallet-connect-dApp-test\.env.local
I was amazed that `git` handles this correctly. On MacOS you'll get a `chia-wallet-connect-dApp-test` directory regardless of the case in GitHub

2023-06-14 21:07 UTC, Rigidity commented
@roybotbot are you able to fix conflicts & remove the image file path rename that 404's so we can get this merged

2023-06-15 05:00 UTC, danieljperry approved these changes
lgtm

2023-06-15 05:56 UTC, danieljperry approved these changes

2023-06-15 05:57 UTC, hoffmang9 approved these changes
Lgtm

2023-06-15 05:57 UTC, merged