Timelord Contest Submission
Chia-Network/chia-docs pull request #591
Opened 2024-06-01 01:51 UTC by braunswag

A massive thank you to Slowesttimelord for his help!

2024-06-03 17:16 UTC, BrandtH22 requested changes

2024-06-03 17:16 UTC, BrandtH22 commented on docs/academy/blockchain-basics/transaction-basics.md
> +A. The transaction fee gets burned.
This line will need two spaces added to the end of it to ensure the list items are separated into a list (1/3)

2024-06-03 17:16 UTC, BrandtH22 commented on docs/academy/blockchain-basics/transaction-basics.md
> +B. It goes to the farmer that formed the block.
This line will need two spaces added to the end of it to ensure the list items are separated into a list (2/3)

2024-06-03 17:16 UTC, BrandtH22 commented on docs/academy/blockchain-basics/transaction-basics.md
> +C. It goes to the receiver of the transaction.
This line will need two spaces added to the end of it to ensure the list items are separated into a list (3/3)

2024-06-04 16:04 UTC, SlowestTimelord commented on docs/academy/blockchain-basics/transaction-basics.md
> +slug: /transactions-basics
The slug should match the file name as well, removing the `s` from `transactions`

2024-07-18 21:10 UTC, BrandtH22 commented
Hey Austin, as relayed in DMs we have made note of this content and will be using it in other academy lessons so this pr will be closed as the page will not be merged as is. Let us know if any questions arise and thank you for the contribution!

2024-07-18 21:10 UTC, closed without merging