Add new information about the coin set model.
Chia-Network/chia-docs pull request #94
Opened 2022-03-06 03:04 UTC by danieljperry

2022-03-06 19:59 UTC, hoffmang9 requested changes
Looks good with two nits.

2022-03-06 19:59 UTC, hoffmang9 commented on docs/04coin-set-model/coin_set_vs_account.md
> +Note, however, that smart coins _could_ be designed such that multiple people could spent the same coin, which would potentially reduce determinism for those coins.
Should be `could spend`

2022-03-06 19:59 UTC, hoffmang9 commented on docs/04coin-set-model/coin_set_vs_account.md
> +In the account model used in many blockchains such as Ethereum, Solana and EOS, balances are kept in accounts. These are permanent data structures which do not get destroyed when they send funds.
Lets replace EOS with Algorand

2022-03-07 00:14 UTC, danieljperry commented
Nits updated.

2022-03-07 00:38 UTC, hoffmang9 approved these changes
lgtm

2022-03-07 00:38 UTC, merged